---
conf.py:
  copyright: 2022
  project: dreipunktnull Glossar
  version: 3.1
  latex_documents:
  - - Index
      - dpn_glossary.tex
      - dreipunktnull Glossar Extension
      - Daniel Dorndorf
      - manual
  html_theme_options:
    github_repository: featdd/dpn_glossary
    github_branch: master
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
    t3start:
    - http://docs.typo3.org/typo3cms/GettingStartedTutorial/
    - null
    t3editors:
    - http://docs.typo3.org/typo3cms/EditorsTutorial/
    - null
...
